name: itec_t3nsa
description: Project for iTEC
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  image_picker: ^0.8.7+1
  image: ^4.0.15
  flutter_image_compress: ^1.1.3
  google_ml_kit: ^0.13.0
  firebase_core: ^2.9.0
  flutter_easyloading: ^3.0.5
  cloud_firestore: ^4.5.0
  flex_color_scheme: ^6.1.2
  google_fonts: ^4.0.3
  flutter_form_builder: ^7.8.0
  form_builder_validators: ^8.5.0
  octo_image: ^1.0.2
  cached_network_image: ^3.2.3
  fan_carousel_image_slider: ^0.1.2
  flutter_staggered_grid_view: ^0.6.2
  firebase_storage: ^11.1.0
  get: ^4.6.5
  fluttericon: ^2.0.0
  firebase_auth: ^4.4.0
  logger: ^1.3.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:
  assets:
    - assets/
  uses-material-design: true
