name: itec_t3nsa
description: Project for iTEC
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  image_picker: ^0.8.7+1
  image: ^4.0.15
  flutter_image_compress: ^1.1.3
  google_ml_kit: ^0.13.0
  firebase_core: ^2.9.0
  http: ^0.13.5
  get: ^4.6.5
  logger: ^1.3.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  pigeon: ^9.1.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:
  assets:
    - assets/
  uses-material-design: true
